language: python
python:
- '3.5'
sudo: required
branches:
  only:
  - pelican
env:
  global:
  - secure: V8YTDdO3J/iGhimGHrGauCrnBXKZaDpvjm9Sqq742mdO5On5wHjlZ8iDg70k4obqaPU/N2/k0/pXCuFh4K9DM3vn1U4SqCck2gN3iDp47l6zA1bY1/Cff3IOUGlz6mz++rkpb+CJ69ycSgWKY8Ff+tdRNw/dgjZIp921MO9JgO9k/iT6MBb25Eyndx4TA5lzuEREB9EEoyJatOdmHltafA2unyNbagld7E1H/8+DdCNUmdPOqCGsu7YmoFwQCH27RBufjRcEp/wT6NevhdL55W3yhZRrPpMatJR1hrDUawNFG9whOIJSeOVnc+GsrtQiuuehe8Csz4B1LW8pKwGJtgbd5Z7iYR8V470+ImVs3nXCrp6J2cpQs0dDDFfljQQugO52Em9srFhEnPaRzdeIfvWzPfAnxi0GJC0SWNUv+RzMkUwk8TI5NYvC+DUJVduqmBffVuH9O9PVIlafTT3iZV0IjrJ6R1gjwv9L1JaH1WcLjqYGX9BKnHVuh+qoWgrvblTBy1ndopOJDu0sZrkamQUkraop/nNfFSYV48g3LSOvgwqFzI6cbIHw0oU92Q+dijemUtMd+DyIl+kyKPJ+EbGSYWSNmdgOF0goKpQCb77EUJH7MOvfiXAS/iGtpl7tiTx8wCHou2w0DpaYKYvHhfrWMcg2j6wUUZ2M8OepY1Y=
install:
- pip install ghp-import
script
- make publish github
